version: '1.0.0-{build}'

branches:
  only:
  - master
  - /\d+\.\d+\.\d+(-\d+)?/
  
clone_folder: c:\project\pageedit

image:
- Visual Studio 2019

configuration: Release

platform:
- x64

init:
  - set /p RedistVersion=<"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt"
  - ps: $commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: $timestamp = $env:appveyor_repo_commit_timestamp.SubString(0,10)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch, $commit, $timestamp)

clone_script:
- ps: >-
    if(-not $env:appveyor_pull_request_number) {
      git clone -q --depth=1 --branch=$env:appveyor_repo_branch https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
      git checkout -qf $env:appveyor_repo_commit
    } else {
      git clone -q --depth=1 https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder 
      git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
      git checkout -qf FETCH_HEAD
    }
    
    Set-Location $env:appveyor_build_folder

install:
  - choco install ninja

environment:
  global:
      INNO: C:\Program Files (x86)\Inno Setup 6
      REDIST: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\%RedistVersion%\vcredist_%PLATFORM%.exe
      DOWNLOAD: https://github.com/dougmassay/win-qtwebkit-5.212/releases/download/v5.212-1/MyQt%PLATFORM%_5.12.9_VS2017_WE.7z
      QT: C:\MyQtx64_WE\Qt5.12.9
      GDRIVE: https://github.com/dougmassay/win-qtwebkit-5.212/releases/download/v5.212-1/gdrive-windows-x64.exe
      GDRIVE_REFRESH_TOKEN:
        secure: +J2q/4lkiBXik5Ttvt06vpNiWBjNIXx+jFnYw1rOR9sLkyksyXGj+NeNKQB8kPwE
      GDRIVE_DIR:
        secure: igOA10tmVbccXE8T92NCKPGcsixGGzyu69QmsBGw6seBOqcQ8+XXm0vjkoLMtrLF
      PYTHON: C:\Python37


before_build:
- cmd: |-
    cp '%REDIST%' installer/
    mkdir build
    cd ..\..
    curl.exe -L -o webkit.7z %DOWNLOAD%
    7z x webkit.7z -y
    set PATH=%PYTHON%;%PYTHON%\Scripts;%QT%\bin;%INNO%;%PATH%
    echo 'PATH = %PATH%'
    cd project\pageedit\build
    curl.exe -L -o gdrive.exe %GDRIVE%
    c:\project\pageedit\build\gdrive.exe version
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM% -vcvars_ver=14.1
    cmake .. -G "Ninja" -DWIN_INSTALLER_USE_64BIT_CRT=1 -DDEPLOY_SFX=1 -DCMAKE_BUILD_TYPE=%configuration% -DQt5_DIR=%QT%\lib\cmake\Qt5

    
build_script:
- cmd: |-
    ninja -j4

after_build:
- cmd: |-
    ninja -j4 deployinstaller

deploy_script:
- ps: >-
    if(-not $env:appveyor_pull_request_number) {
        python --version
        c:\project\pageedit\build\gdrive.exe version
        python ..\ci_scripts\gddeploy.py
    }
 
#artifacts:
#    path: build\deploy\*.exe
