#############################################################################
# Makefile for building: PageEdit.app/Contents/MacOS/PageEdit
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  PageEdit.pro
# Template: app
# Command: /Users/kbhend/Qt512/bin/qmake -o Makefile PageEdit.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt512/lib/QtWebEngineWidgets.framework/Headers -I../../Qt512/lib/QtPrintSupport.framework/Headers -I../../Qt512/lib/QtWidgets.framework/Headers -I../../Qt512/lib/QtWebEngine.framework/Headers -I../../Qt512/lib/QtWebEngineCore.framework/Headers -I../../Qt512/lib/QtQuick.framework/Headers -I../../Qt512/lib/QtGui.framework/Headers -I../../Qt512/lib/QtWebChannel.framework/Headers -I../../Qt512/lib/QtQml.framework/Headers -I../../Qt512/lib/QtNetwork.framework/Headers -I../../Qt512/lib/QtPositioning.framework/Headers -I../../Qt512/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt512/mkspecs/macx-clang -F/Users/kbhend/Qt512/lib
QMAKE         = /Users/kbhend/Qt512/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/kbhend/Qt512/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/kbhend/Qt512/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PageEdit1.0.0
DISTDIR = /Users/kbhend/Desktop/PageEditor/.tmp/PageEdit1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/kbhend/Qt512/lib
LIBS          = $(SUBLIBS) -F/Users/kbhend/Qt512/lib -framework QtWebEngineWidgets -framework QtPrintSupport -framework QtWidgets -framework QtWebEngine -framework QtWebEngineCore -framework QtQuick -framework QtGui -framework QtWebChannel -framework QtQml -framework QtNetwork -framework QtPositioning -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainApplication.cpp \
		MainWindow.cpp \
		Inspector.cpp \
		SelectCharacter.cpp \
		SettingsStore.cpp \
		Utility.cpp \
		WebPageEdit.cpp \
		WebViewEdit.cpp qrc_icons.cpp \
		qrc_javascript.cpp \
		moc_MainApplication.cpp \
		moc_MainWindow.cpp \
		moc_Inspector.cpp \
		moc_SelectCharacter.cpp \
		moc_SettingsStore.cpp \
		moc_WebPageEdit.cpp \
		moc_WebViewEdit.cpp
OBJECTS       = main.o \
		MainApplication.o \
		MainWindow.o \
		Inspector.o \
		SelectCharacter.o \
		SettingsStore.o \
		Utility.o \
		WebPageEdit.o \
		WebViewEdit.o \
		qrc_icons.o \
		qrc_javascript.o \
		moc_MainApplication.o \
		moc_MainWindow.o \
		moc_Inspector.o \
		moc_SelectCharacter.o \
		moc_SettingsStore.o \
		moc_WebPageEdit.o \
		moc_WebViewEdit.o
DIST          = ../../Qt512/mkspecs/features/spec_pre.prf \
		../../Qt512/mkspecs/qdevice.pri \
		../../Qt512/mkspecs/features/device_config.prf \
		../../Qt512/mkspecs/common/unix.conf \
		../../Qt512/mkspecs/common/mac.conf \
		../../Qt512/mkspecs/common/macx.conf \
		../../Qt512/mkspecs/common/sanitize.conf \
		../../Qt512/mkspecs/common/gcc-base.conf \
		../../Qt512/mkspecs/common/gcc-base-mac.conf \
		../../Qt512/mkspecs/common/clang.conf \
		../../Qt512/mkspecs/common/clang-mac.conf \
		../../Qt512/mkspecs/qconfig.pri \
		../../Qt512/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt512/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt512/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt512/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_charts.pri \
		../../Qt512/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt512/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_core.pri \
		../../Qt512/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt512/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt512/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_designer.pri \
		../../Qt512/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt512/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_gui.pri \
		../../Qt512/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_help.pri \
		../../Qt512/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_location.pri \
		../../Qt512/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt512/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_network.pri \
		../../Qt512/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt512/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt512/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt512/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt512/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt512/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt512/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qml.pri \
		../../Qt512/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quick.pri \
		../../Qt512/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt512/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt512/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt512/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_script.pri \
		../../Qt512/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt512/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt512/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt512/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_sql.pri \
		../../Qt512/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_svg.pri \
		../../Qt512/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt512/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt512/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt512/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt512/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt512/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt512/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt512/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt512/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webview.pri \
		../../Qt512/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_xml.pri \
		../../Qt512/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt512/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt512/mkspecs/features/qt_functions.prf \
		../../Qt512/mkspecs/features/qt_config.prf \
		../../Qt512/mkspecs/macx-clang/qmake.conf \
		../../Qt512/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt512/mkspecs/features/exclusive_builds.prf \
		../../Qt512/mkspecs/features/mac/sdk.prf \
		../../Qt512/mkspecs/features/toolchain.prf \
		../../Qt512/mkspecs/features/mac/toolchain.prf \
		../../Qt512/mkspecs/features/default_pre.prf \
		../../Qt512/mkspecs/features/mac/default_pre.prf \
		../../Qt512/mkspecs/features/resolve_config.prf \
		../../Qt512/mkspecs/features/default_post.prf \
		../../Qt512/mkspecs/features/mac/default_post.prf \
		../../Qt512/mkspecs/features/mac/objective_c.prf \
		../../Qt512/mkspecs/features/mac/mac.prf \
		../../Qt512/mkspecs/features/warn_on.prf \
		../../Qt512/mkspecs/features/qt.prf \
		../../Qt512/mkspecs/features/resources.prf \
		../../Qt512/mkspecs/features/moc.prf \
		../../Qt512/mkspecs/features/unix/opengl.prf \
		../../Qt512/mkspecs/features/uic.prf \
		../../Qt512/mkspecs/features/unix/thread.prf \
		../../Qt512/mkspecs/features/qmake_use.prf \
		../../Qt512/mkspecs/features/file_copies.prf \
		../../Qt512/mkspecs/features/mac/rez.prf \
		../../Qt512/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt512/mkspecs/features/testcase_targets.prf \
		../../Qt512/mkspecs/features/exceptions.prf \
		../../Qt512/mkspecs/features/yacc.prf \
		../../Qt512/mkspecs/features/lex.prf \
		PageEdit.pro MainApplication.h \
		MainWindow.h \
		ElementIndex.h \
		Inspector.h \
		pageedit_exception.h \
		SelectCharacter.h \
		SettingsStore.h \
		Utility.h \
		WebPageEdit.h \
		WebViewEdit.h \
		Zoomable.h \
		Viewer.h main.cpp \
		MainApplication.cpp \
		MainWindow.cpp \
		Inspector.cpp \
		SelectCharacter.cpp \
		SettingsStore.cpp \
		Utility.cpp \
		WebPageEdit.cpp \
		WebViewEdit.cpp
QMAKE_TARGET  = PageEdit
DESTDIR       = 
TARGET        = PageEdit.app/Contents/MacOS/PageEdit

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/kbhend/Desktop/PageEditor/PageEdit.pro


include /Users/kbhend/Qt512/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

PageEdit.app/Contents/MacOS/PageEdit: ui_main.h ui_SelectCharacter.h $(OBJECTS)  
	@test -d PageEdit.app/Contents/MacOS/ || mkdir -p PageEdit.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PageEdit.pro ../../Qt512/mkspecs/macx-clang/qmake.conf ../../Qt512/mkspecs/features/spec_pre.prf \
		../../Qt512/mkspecs/qdevice.pri \
		../../Qt512/mkspecs/features/device_config.prf \
		../../Qt512/mkspecs/common/unix.conf \
		../../Qt512/mkspecs/common/mac.conf \
		../../Qt512/mkspecs/common/macx.conf \
		../../Qt512/mkspecs/common/sanitize.conf \
		../../Qt512/mkspecs/common/gcc-base.conf \
		../../Qt512/mkspecs/common/gcc-base-mac.conf \
		../../Qt512/mkspecs/common/clang.conf \
		../../Qt512/mkspecs/common/clang-mac.conf \
		../../Qt512/mkspecs/qconfig.pri \
		../../Qt512/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt512/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt512/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt512/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt512/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_charts.pri \
		../../Qt512/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt512/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_core.pri \
		../../Qt512/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt512/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt512/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_designer.pri \
		../../Qt512/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt512/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_gui.pri \
		../../Qt512/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_help.pri \
		../../Qt512/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_location.pri \
		../../Qt512/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt512/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_network.pri \
		../../Qt512/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt512/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt512/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt512/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt512/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt512/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt512/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt512/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qml.pri \
		../../Qt512/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt512/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quick.pri \
		../../Qt512/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt512/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt512/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt512/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_script.pri \
		../../Qt512/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt512/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt512/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt512/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt512/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_sql.pri \
		../../Qt512/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_svg.pri \
		../../Qt512/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt512/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt512/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt512/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt512/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt512/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt512/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt512/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt512/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_webview.pri \
		../../Qt512/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt512/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_xml.pri \
		../../Qt512/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt512/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt512/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt512/mkspecs/features/qt_functions.prf \
		../../Qt512/mkspecs/features/qt_config.prf \
		../../Qt512/mkspecs/macx-clang/qmake.conf \
		../../Qt512/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt512/mkspecs/features/exclusive_builds.prf \
		../../Qt512/mkspecs/features/mac/sdk.prf \
		../../Qt512/mkspecs/features/toolchain.prf \
		../../Qt512/mkspecs/features/mac/toolchain.prf \
		../../Qt512/mkspecs/features/default_pre.prf \
		../../Qt512/mkspecs/features/mac/default_pre.prf \
		../../Qt512/mkspecs/features/resolve_config.prf \
		../../Qt512/mkspecs/features/default_post.prf \
		../../Qt512/mkspecs/features/mac/default_post.prf \
		../../Qt512/mkspecs/features/mac/objective_c.prf \
		../../Qt512/mkspecs/features/mac/mac.prf \
		../../Qt512/mkspecs/features/warn_on.prf \
		../../Qt512/mkspecs/features/qt.prf \
		../../Qt512/mkspecs/features/resources.prf \
		../../Qt512/mkspecs/features/moc.prf \
		../../Qt512/mkspecs/features/unix/opengl.prf \
		../../Qt512/mkspecs/features/uic.prf \
		../../Qt512/mkspecs/features/unix/thread.prf \
		../../Qt512/mkspecs/features/qmake_use.prf \
		../../Qt512/mkspecs/features/file_copies.prf \
		../../Qt512/mkspecs/features/mac/rez.prf \
		../../Qt512/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt512/mkspecs/features/testcase_targets.prf \
		../../Qt512/mkspecs/features/exceptions.prf \
		../../Qt512/mkspecs/features/yacc.prf \
		../../Qt512/mkspecs/features/lex.prf \
		PageEdit.pro \
		icons/icons.qrc \
		javascript/javascript.qrc \
		../../Qt512/lib/QtWebEngineWidgets.framework/QtWebEngineWidgets.prl \
		../../Qt512/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		../../Qt512/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt512/lib/QtWebEngine.framework/QtWebEngine.prl \
		../../Qt512/lib/QtWebEngineCore.framework/QtWebEngineCore.prl \
		../../Qt512/lib/QtQuick.framework/QtQuick.prl \
		../../Qt512/lib/QtGui.framework/QtGui.prl \
		../../Qt512/lib/QtWebChannel.framework/QtWebChannel.prl \
		../../Qt512/lib/QtQml.framework/QtQml.prl \
		../../Qt512/lib/QtNetwork.framework/QtNetwork.prl \
		../../Qt512/lib/QtPositioning.framework/QtPositioning.prl \
		../../Qt512/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile PageEdit.pro
../../Qt512/mkspecs/features/spec_pre.prf:
../../Qt512/mkspecs/qdevice.pri:
../../Qt512/mkspecs/features/device_config.prf:
../../Qt512/mkspecs/common/unix.conf:
../../Qt512/mkspecs/common/mac.conf:
../../Qt512/mkspecs/common/macx.conf:
../../Qt512/mkspecs/common/sanitize.conf:
../../Qt512/mkspecs/common/gcc-base.conf:
../../Qt512/mkspecs/common/gcc-base-mac.conf:
../../Qt512/mkspecs/common/clang.conf:
../../Qt512/mkspecs/common/clang-mac.conf:
../../Qt512/mkspecs/qconfig.pri:
../../Qt512/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt512/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt512/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt512/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt512/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt512/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt512/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt512/mkspecs/modules/qt_lib_3drender.pri:
../../Qt512/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt512/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt512/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt512/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt512/mkspecs/modules/qt_lib_charts.pri:
../../Qt512/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt512/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt512/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt512/mkspecs/modules/qt_lib_core.pri:
../../Qt512/mkspecs/modules/qt_lib_core_private.pri:
../../Qt512/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt512/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt512/mkspecs/modules/qt_lib_dbus.pri:
../../Qt512/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt512/mkspecs/modules/qt_lib_designer.pri:
../../Qt512/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt512/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt512/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt512/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt512/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_gui.pri:
../../Qt512/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt512/mkspecs/modules/qt_lib_help.pri:
../../Qt512/mkspecs/modules/qt_lib_help_private.pri:
../../Qt512/mkspecs/modules/qt_lib_location.pri:
../../Qt512/mkspecs/modules/qt_lib_location_private.pri:
../../Qt512/mkspecs/modules/qt_lib_macextras.pri:
../../Qt512/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt512/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt512/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt512/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt512/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt512/mkspecs/modules/qt_lib_network.pri:
../../Qt512/mkspecs/modules/qt_lib_network_private.pri:
../../Qt512/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt512/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt512/mkspecs/modules/qt_lib_nfc.pri:
../../Qt512/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt512/mkspecs/modules/qt_lib_opengl.pri:
../../Qt512/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt512/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt512/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt512/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt512/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_positioning.pri:
../../Qt512/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt512/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt512/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt512/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt512/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt512/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt512/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt512/mkspecs/modules/qt_lib_qml.pri:
../../Qt512/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt512/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt512/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt512/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt512/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt512/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt512/mkspecs/modules/qt_lib_quick.pri:
../../Qt512/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt512/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt512/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt512/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt512/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt512/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt512/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt512/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt512/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt512/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt512/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt512/mkspecs/modules/qt_lib_repparser.pri:
../../Qt512/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt512/mkspecs/modules/qt_lib_script.pri:
../../Qt512/mkspecs/modules/qt_lib_script_private.pri:
../../Qt512/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt512/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt512/mkspecs/modules/qt_lib_scxml.pri:
../../Qt512/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt512/mkspecs/modules/qt_lib_sensors.pri:
../../Qt512/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt512/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt512/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt512/mkspecs/modules/qt_lib_serialport.pri:
../../Qt512/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt512/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_sql.pri:
../../Qt512/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt512/mkspecs/modules/qt_lib_svg.pri:
../../Qt512/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt512/mkspecs/modules/qt_lib_testlib.pri:
../../Qt512/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt512/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt512/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt512/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt512/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt512/mkspecs/modules/qt_lib_uitools.pri:
../../Qt512/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt512/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt512/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt512/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webengine.pri:
../../Qt512/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt512/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt512/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webkit.pri:
../../Qt512/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt512/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt512/mkspecs/modules/qt_lib_websockets.pri:
../../Qt512/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt512/mkspecs/modules/qt_lib_webview.pri:
../../Qt512/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt512/mkspecs/modules/qt_lib_widgets.pri:
../../Qt512/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt512/mkspecs/modules/qt_lib_xml.pri:
../../Qt512/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt512/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt512/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt512/mkspecs/features/qt_functions.prf:
../../Qt512/mkspecs/features/qt_config.prf:
../../Qt512/mkspecs/macx-clang/qmake.conf:
../../Qt512/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt512/mkspecs/features/exclusive_builds.prf:
../../Qt512/mkspecs/features/mac/sdk.prf:
../../Qt512/mkspecs/features/toolchain.prf:
../../Qt512/mkspecs/features/mac/toolchain.prf:
../../Qt512/mkspecs/features/default_pre.prf:
../../Qt512/mkspecs/features/mac/default_pre.prf:
../../Qt512/mkspecs/features/resolve_config.prf:
../../Qt512/mkspecs/features/default_post.prf:
../../Qt512/mkspecs/features/mac/default_post.prf:
../../Qt512/mkspecs/features/mac/objective_c.prf:
../../Qt512/mkspecs/features/mac/mac.prf:
../../Qt512/mkspecs/features/warn_on.prf:
../../Qt512/mkspecs/features/qt.prf:
../../Qt512/mkspecs/features/resources.prf:
../../Qt512/mkspecs/features/moc.prf:
../../Qt512/mkspecs/features/unix/opengl.prf:
../../Qt512/mkspecs/features/uic.prf:
../../Qt512/mkspecs/features/unix/thread.prf:
../../Qt512/mkspecs/features/qmake_use.prf:
../../Qt512/mkspecs/features/file_copies.prf:
../../Qt512/mkspecs/features/mac/rez.prf:
../../Qt512/mkspecs/features/mac/asset_catalogs.prf:
../../Qt512/mkspecs/features/testcase_targets.prf:
../../Qt512/mkspecs/features/exceptions.prf:
../../Qt512/mkspecs/features/yacc.prf:
../../Qt512/mkspecs/features/lex.prf:
PageEdit.pro:
icons/icons.qrc:
javascript/javascript.qrc:
../../Qt512/lib/QtWebEngineWidgets.framework/QtWebEngineWidgets.prl:
../../Qt512/lib/QtPrintSupport.framework/QtPrintSupport.prl:
../../Qt512/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt512/lib/QtWebEngine.framework/QtWebEngine.prl:
../../Qt512/lib/QtWebEngineCore.framework/QtWebEngineCore.prl:
../../Qt512/lib/QtQuick.framework/QtQuick.prl:
../../Qt512/lib/QtGui.framework/QtGui.prl:
../../Qt512/lib/QtWebChannel.framework/QtWebChannel.prl:
../../Qt512/lib/QtQml.framework/QtQml.prl:
../../Qt512/lib/QtNetwork.framework/QtNetwork.prl:
../../Qt512/lib/QtPositioning.framework/QtPositioning.prl:
../../Qt512/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PageEdit.pro

qmake_all: FORCE

PageEdit.app/Contents/PkgInfo: 
	@test -d PageEdit.app/Contents || mkdir -p PageEdit.app/Contents
	@$(DEL_FILE) PageEdit.app/Contents/PkgInfo
	@echo "APPL????" > PageEdit.app/Contents/PkgInfo
PageEdit.app/Contents/Resources/empty.lproj: 
	@test -d PageEdit.app/Contents/Resources || mkdir -p PageEdit.app/Contents/Resources
	@touch PageEdit.app/Contents/Resources/empty.lproj
	
PageEdit.app/Contents/Info.plist: 
	@test -d PageEdit.app/Contents || mkdir -p PageEdit.app/Contents
	@$(DEL_FILE) PageEdit.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.PageEdit,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.PageEdit,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,PageEdit,g" -e "s,@LIBRARY@,PageEdit,g" -e "s,\$${EXECUTABLE_NAME},PageEdit,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt512/mkspecs/macx-clang/Info.plist.app >PageEdit.app/Contents/Info.plist

all: Makefile \
		PageEdit.app/Contents/PkgInfo \
		PageEdit.app/Contents/Resources/empty.lproj \
		PageEdit.app/Contents/Info.plist PageEdit.app/Contents/MacOS/PageEdit

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons/icons.qrc javascript/javascript.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt512/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MainApplication.h MainWindow.h ElementIndex.h Inspector.h pageedit_exception.h SelectCharacter.h SettingsStore.h Utility.h WebPageEdit.h WebViewEdit.h Zoomable.h Viewer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MainApplication.cpp MainWindow.cpp Inspector.cpp SelectCharacter.cpp SettingsStore.cpp Utility.cpp WebPageEdit.cpp WebViewEdit.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.ui SelectCharacter.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r PageEdit.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_icons.cpp qrc_javascript.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp qrc_javascript.cpp
qrc_icons.cpp: icons/icons.qrc \
		../../Qt512/bin/rcc \
		icons/insert-special-character_48px.png \
		icons/edit-redo_48px.png \
		icons/format-justify-fill_48px.png \
		icons/format-text-italic_48px.png \
		icons/format-text-subscript_48px.png \
		icons/format-text-bold_48px.png \
		icons/heading-5_48px.png \
		icons/format-case-lowercase_48px.png \
		icons/format-indent-less_48px.png \
		icons/edit-undo_48px.png \
		icons/document-save_48px.png \
		icons/format-case-uppercase_48px.png \
		icons/heading-6_48px.png \
		icons/format-justify-left_48px.png \
		icons/format-text-underline_48px.png \
		icons/heading-1_48px.png \
		icons/format-justify-center_48px.png \
		icons/heading-all_48px.png \
		icons/reload-page_48px.png \
		icons/heading-normal_48px.png \
		icons/format-case-capitalize_48px.png \
		icons/edit-paste_48px.png \
		icons/heading-2_48px.png \
		icons/edit-select-all_48px.png \
		icons/document-open_48px.png \
		icons/edit-copy_48px.png \
		icons/edit-cut_48px.png \
		icons/format-case-titlecase_48px.png \
		icons/format-indent-more_48px.png \
		icons/heading-3_48px.png \
		icons/insert-numbered-list_48px.png \
		icons/insert-bullet-list_48px.png \
		icons/format-text-strikethrough_48px.png \
		icons/format-text-superscript_48px.png \
		icons/format-justify-right_48px.png \
		icons/heading-4_48px.png \
		icons/inspect_48px.png
	/Users/kbhend/Qt512/bin/rcc -name icons icons/icons.qrc -o qrc_icons.cpp

qrc_javascript.cpp: javascript/javascript.qrc \
		../../Qt512/bin/rcc \
		javascript/book_view_current_location.js \
		javascript/jquery.wrapSelection.js \
		javascript/get_block.js \
		javascript/jquery-2.2.4.min.js \
		javascript/jquery.scrollTo-2.1.2-min.js \
		javascript/format_block.js
	/Users/kbhend/Qt512/bin/rcc -name javascript javascript/javascript.qrc -o qrc_javascript.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt512/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../Qt512/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainApplication.cpp moc_MainWindow.cpp moc_Inspector.cpp moc_SelectCharacter.cpp moc_SettingsStore.cpp moc_WebPageEdit.cpp moc_WebViewEdit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainApplication.cpp moc_MainWindow.cpp moc_Inspector.cpp moc_SelectCharacter.cpp moc_SettingsStore.cpp moc_WebPageEdit.cpp moc_WebViewEdit.cpp
moc_MainApplication.cpp: MainApplication.h \
		../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		moc_predefs.h \
		../../Qt512/bin/moc
	/Users/kbhend/Qt512/bin/moc $(DEFINES) --include /Users/kbhend/Desktop/PageEditor/moc_predefs.h -I/Users/kbhend/Qt512/mkspecs/macx-clang -I/Users/kbhend/Desktop/PageEditor -I/Users/kbhend/Qt512/lib/QtWebEngineWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtPrintSupport.framework/Headers -I/Users/kbhend/Qt512/lib/QtWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngine.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngineCore.framework/Headers -I/Users/kbhend/Qt512/lib/QtQuick.framework/Headers -I/Users/kbhend/Qt512/lib/QtGui.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebChannel.framework/Headers -I/Users/kbhend/Qt512/lib/QtQml.framework/Headers -I/Users/kbhend/Qt512/lib/QtNetwork.framework/Headers -I/Users/kbhend/Qt512/lib/QtPositioning.framework/Headers -I/Users/kbhend/Qt512/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kbhend/Qt512/lib MainApplication.h -o moc_MainApplication.cpp

moc_MainWindow.cpp: MainWindow.h \
		ui_main.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt512/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QAction \
		../../Qt512/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt512/lib/QtCore.framework/Headers/QMap \
		../../Qt512/lib/QtCore.framework/Headers/qmap.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt512/lib/QtWidgets.framework/Headers/qmainwindow.h \
		Viewer.h \
		Zoomable.h \
		ElementIndex.h \
		Inspector.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QDockWidget \
		../../Qt512/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt512/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt512/lib/QtGui.framework/Headers/qevent.h \
		../../Qt512/lib/QtCore.framework/Headers/QSize \
		../../Qt512/lib/QtCore.framework/Headers/qsize.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt512/lib/QtWidgets.framework/Headers/qboxlayout.h \
		moc_predefs.h \
		../../Qt512/bin/moc
	/Users/kbhend/Qt512/bin/moc $(DEFINES) --include /Users/kbhend/Desktop/PageEditor/moc_predefs.h -I/Users/kbhend/Qt512/mkspecs/macx-clang -I/Users/kbhend/Desktop/PageEditor -I/Users/kbhend/Qt512/lib/QtWebEngineWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtPrintSupport.framework/Headers -I/Users/kbhend/Qt512/lib/QtWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngine.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngineCore.framework/Headers -I/Users/kbhend/Qt512/lib/QtQuick.framework/Headers -I/Users/kbhend/Qt512/lib/QtGui.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebChannel.framework/Headers -I/Users/kbhend/Qt512/lib/QtQml.framework/Headers -I/Users/kbhend/Qt512/lib/QtNetwork.framework/Headers -I/Users/kbhend/Qt512/lib/QtPositioning.framework/Headers -I/Users/kbhend/Qt512/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kbhend/Qt512/lib MainWindow.h -o moc_MainWindow.cpp

moc_Inspector.cpp: Inspector.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QDockWidget \
		../../Qt512/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt512/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt512/lib/QtGui.framework/Headers/qevent.h \
		../../Qt512/lib/QtCore.framework/Headers/QSize \
		../../Qt512/lib/QtCore.framework/Headers/qsize.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt512/lib/QtWidgets.framework/Headers/qboxlayout.h \
		moc_predefs.h \
		../../Qt512/bin/moc
	/Users/kbhend/Qt512/bin/moc $(DEFINES) --include /Users/kbhend/Desktop/PageEditor/moc_predefs.h -I/Users/kbhend/Qt512/mkspecs/macx-clang -I/Users/kbhend/Desktop/PageEditor -I/Users/kbhend/Qt512/lib/QtWebEngineWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtPrintSupport.framework/Headers -I/Users/kbhend/Qt512/lib/QtWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngine.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngineCore.framework/Headers -I/Users/kbhend/Qt512/lib/QtQuick.framework/Headers -I/Users/kbhend/Qt512/lib/QtGui.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebChannel.framework/Headers -I/Users/kbhend/Qt512/lib/QtQml.framework/Headers -I/Users/kbhend/Qt512/lib/QtNetwork.framework/Headers -I/Users/kbhend/Qt512/lib/QtPositioning.framework/Headers -I/Users/kbhend/Qt512/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kbhend/Qt512/lib Inspector.h -o moc_Inspector.cpp

moc_SelectCharacter.cpp: SelectCharacter.h \
		SettingsStore.h \
		../../Qt512/lib/QtGui.framework/Headers/QColor \
		../../Qt512/lib/QtGui.framework/Headers/qcolor.h \
		ui_SelectCharacter.h \
		moc_predefs.h \
		../../Qt512/bin/moc
	/Users/kbhend/Qt512/bin/moc $(DEFINES) --include /Users/kbhend/Desktop/PageEditor/moc_predefs.h -I/Users/kbhend/Qt512/mkspecs/macx-clang -I/Users/kbhend/Desktop/PageEditor -I/Users/kbhend/Qt512/lib/QtWebEngineWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtPrintSupport.framework/Headers -I/Users/kbhend/Qt512/lib/QtWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngine.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngineCore.framework/Headers -I/Users/kbhend/Qt512/lib/QtQuick.framework/Headers -I/Users/kbhend/Qt512/lib/QtGui.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebChannel.framework/Headers -I/Users/kbhend/Qt512/lib/QtQml.framework/Headers -I/Users/kbhend/Qt512/lib/QtNetwork.framework/Headers -I/Users/kbhend/Qt512/lib/QtPositioning.framework/Headers -I/Users/kbhend/Qt512/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kbhend/Qt512/lib SelectCharacter.h -o moc_SelectCharacter.cpp

moc_SettingsStore.cpp: SettingsStore.h \
		../../Qt512/lib/QtGui.framework/Headers/QColor \
		../../Qt512/lib/QtGui.framework/Headers/qcolor.h \
		moc_predefs.h \
		../../Qt512/bin/moc
	/Users/kbhend/Qt512/bin/moc $(DEFINES) --include /Users/kbhend/Desktop/PageEditor/moc_predefs.h -I/Users/kbhend/Qt512/mkspecs/macx-clang -I/Users/kbhend/Desktop/PageEditor -I/Users/kbhend/Qt512/lib/QtWebEngineWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtPrintSupport.framework/Headers -I/Users/kbhend/Qt512/lib/QtWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngine.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngineCore.framework/Headers -I/Users/kbhend/Qt512/lib/QtQuick.framework/Headers -I/Users/kbhend/Qt512/lib/QtGui.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebChannel.framework/Headers -I/Users/kbhend/Qt512/lib/QtQml.framework/Headers -I/Users/kbhend/Qt512/lib/QtNetwork.framework/Headers -I/Users/kbhend/Qt512/lib/QtPositioning.framework/Headers -I/Users/kbhend/Qt512/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kbhend/Qt512/lib SettingsStore.h -o moc_SettingsStore.cpp

moc_WebPageEdit.cpp: WebPageEdit.h \
		../../Qt512/lib/QtCore.framework/Headers/QObject \
		../../Qt512/lib/QtCore.framework/Headers/qobject.h \
		../../Qt512/lib/QtCore.framework/Headers/QUrl \
		../../Qt512/lib/QtCore.framework/Headers/qurl.h \
		moc_predefs.h \
		../../Qt512/bin/moc
	/Users/kbhend/Qt512/bin/moc $(DEFINES) --include /Users/kbhend/Desktop/PageEditor/moc_predefs.h -I/Users/kbhend/Qt512/mkspecs/macx-clang -I/Users/kbhend/Desktop/PageEditor -I/Users/kbhend/Qt512/lib/QtWebEngineWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtPrintSupport.framework/Headers -I/Users/kbhend/Qt512/lib/QtWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngine.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngineCore.framework/Headers -I/Users/kbhend/Qt512/lib/QtQuick.framework/Headers -I/Users/kbhend/Qt512/lib/QtGui.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebChannel.framework/Headers -I/Users/kbhend/Qt512/lib/QtQml.framework/Headers -I/Users/kbhend/Qt512/lib/QtNetwork.framework/Headers -I/Users/kbhend/Qt512/lib/QtPositioning.framework/Headers -I/Users/kbhend/Qt512/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kbhend/Qt512/lib WebPageEdit.h -o moc_WebPageEdit.cpp

moc_WebViewEdit.cpp: WebViewEdit.h \
		../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		WebPageEdit.h \
		../../Qt512/lib/QtCore.framework/Headers/QObject \
		../../Qt512/lib/QtCore.framework/Headers/qobject.h \
		../../Qt512/lib/QtCore.framework/Headers/QUrl \
		../../Qt512/lib/QtCore.framework/Headers/qurl.h \
		Viewer.h \
		Zoomable.h \
		ElementIndex.h \
		moc_predefs.h \
		../../Qt512/bin/moc
	/Users/kbhend/Qt512/bin/moc $(DEFINES) --include /Users/kbhend/Desktop/PageEditor/moc_predefs.h -I/Users/kbhend/Qt512/mkspecs/macx-clang -I/Users/kbhend/Desktop/PageEditor -I/Users/kbhend/Qt512/lib/QtWebEngineWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtPrintSupport.framework/Headers -I/Users/kbhend/Qt512/lib/QtWidgets.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngine.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebEngineCore.framework/Headers -I/Users/kbhend/Qt512/lib/QtQuick.framework/Headers -I/Users/kbhend/Qt512/lib/QtGui.framework/Headers -I/Users/kbhend/Qt512/lib/QtWebChannel.framework/Headers -I/Users/kbhend/Qt512/lib/QtQml.framework/Headers -I/Users/kbhend/Qt512/lib/QtNetwork.framework/Headers -I/Users/kbhend/Qt512/lib/QtPositioning.framework/Headers -I/Users/kbhend/Qt512/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kbhend/Qt512/lib WebViewEdit.h -o moc_WebViewEdit.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_main.h ui_SelectCharacter.h
compiler_uic_clean:
	-$(DEL_FILE) ui_main.h ui_SelectCharacter.h
ui_main.h: main.ui \
		../../Qt512/bin/uic
	/Users/kbhend/Qt512/bin/uic main.ui -o ui_main.h

ui_SelectCharacter.h: SelectCharacter.ui \
		../../Qt512/bin/uic
	/Users/kbhend/Qt512/bin/uic SelectCharacter.ui -o ui_SelectCharacter.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../Qt512/lib/QtCore.framework/Headers/QFileInfo \
		../../Qt512/lib/QtCore.framework/Headers/qfileinfo.h \
		../../Qt512/lib/QtCore.framework/Headers/QDebug \
		../../Qt512/lib/QtCore.framework/Headers/qdebug.h \
		MainApplication.h \
		../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		MainWindow.h \
		ui_main.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt512/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QAction \
		../../Qt512/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt512/lib/QtCore.framework/Headers/QMap \
		../../Qt512/lib/QtCore.framework/Headers/qmap.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt512/lib/QtWidgets.framework/Headers/qmainwindow.h \
		Viewer.h \
		Zoomable.h \
		ElementIndex.h \
		Inspector.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QDockWidget \
		../../Qt512/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt512/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt512/lib/QtGui.framework/Headers/qevent.h \
		../../Qt512/lib/QtCore.framework/Headers/QSize \
		../../Qt512/lib/QtCore.framework/Headers/qsize.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt512/lib/QtWidgets.framework/Headers/qboxlayout.h \
		Utility.h \
		../../Qt512/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt512/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QFileDialog \
		../../Qt512/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt512/lib/QtGui.framework/Headers/QKeySequence \
		../../Qt512/lib/QtGui.framework/Headers/qkeysequence.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainApplication.o: MainApplication.cpp MainApplication.h \
		../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainApplication.o MainApplication.cpp

MainWindow.o: MainWindow.cpp ../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt512/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt512/lib/QtGui.framework/Headers/qevent.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt512/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt512/lib/QtGui.framework/Headers/QClipboard \
		../../Qt512/lib/QtGui.framework/Headers/qclipboard.h \
		../../Qt512/lib/QtCore.framework/Headers/QMimedata \
		../../Qt512/lib/QtCore.framework/Headers/qmimedata.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt512/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt512/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Qt512/lib/QtWidgets.framework/Headers/QToolBar \
		../../Qt512/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt512/lib/QtCore.framework/Headers/QDir \
		../../Qt512/lib/QtCore.framework/Headers/qdir.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QFileDialog \
		../../Qt512/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt512/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt512/lib/QtCore.framework/Headers/QRegularExpression \
		../../Qt512/lib/QtCore.framework/Headers/qregularexpression.h \
		../../Qt512/lib/QtCore.framework/Headers/QRegularExpressionMatch \
		../../Qt512/lib/QtCore.framework/Headers/QTimer \
		../../Qt512/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt512/lib/QtCore.framework/Headers/QDebug \
		../../Qt512/lib/QtCore.framework/Headers/qdebug.h \
		MainWindow.h \
		ui_main.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt512/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QAction \
		../../Qt512/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt512/lib/QtCore.framework/Headers/QMap \
		../../Qt512/lib/QtCore.framework/Headers/qmap.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt512/lib/QtWidgets.framework/Headers/qmainwindow.h \
		Viewer.h \
		Zoomable.h \
		ElementIndex.h \
		Inspector.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QDockWidget \
		../../Qt512/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt512/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt512/lib/QtCore.framework/Headers/QSize \
		../../Qt512/lib/QtCore.framework/Headers/qsize.h \
		SettingsStore.h \
		../../Qt512/lib/QtGui.framework/Headers/QColor \
		../../Qt512/lib/QtGui.framework/Headers/qcolor.h \
		Utility.h \
		../../Qt512/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt512/lib/QtCore.framework/Headers/qcoreapplication.h \
		WebViewEdit.h \
		WebPageEdit.h \
		../../Qt512/lib/QtCore.framework/Headers/QObject \
		../../Qt512/lib/QtCore.framework/Headers/qobject.h \
		../../Qt512/lib/QtCore.framework/Headers/QUrl \
		../../Qt512/lib/QtCore.framework/Headers/qurl.h \
		SelectCharacter.h \
		ui_SelectCharacter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

Inspector.o: Inspector.cpp ../../Qt512/lib/QtCore.framework/Headers/QByteArray \
		../../Qt512/lib/QtCore.framework/Headers/qbytearray.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt512/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt512/lib/QtCore.framework/Headers/QDebug \
		../../Qt512/lib/QtCore.framework/Headers/qdebug.h \
		SettingsStore.h \
		../../Qt512/lib/QtGui.framework/Headers/QColor \
		../../Qt512/lib/QtGui.framework/Headers/qcolor.h \
		Inspector.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QDockWidget \
		../../Qt512/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt512/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt512/lib/QtGui.framework/Headers/qevent.h \
		../../Qt512/lib/QtCore.framework/Headers/QSize \
		../../Qt512/lib/QtCore.framework/Headers/qsize.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt512/lib/QtWidgets.framework/Headers/qboxlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Inspector.o Inspector.cpp

SelectCharacter.o: SelectCharacter.cpp SelectCharacter.h \
		SettingsStore.h \
		../../Qt512/lib/QtGui.framework/Headers/QColor \
		../../Qt512/lib/QtGui.framework/Headers/qcolor.h \
		ui_SelectCharacter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SelectCharacter.o SelectCharacter.cpp

SettingsStore.o: SettingsStore.cpp ../../Qt512/lib/QtCore.framework/Headers/QFile \
		../../Qt512/lib/QtCore.framework/Headers/qfile.h \
		../../Qt512/lib/QtCore.framework/Headers/QDir \
		../../Qt512/lib/QtCore.framework/Headers/qdir.h \
		SettingsStore.h \
		../../Qt512/lib/QtGui.framework/Headers/QColor \
		../../Qt512/lib/QtGui.framework/Headers/qcolor.h \
		Utility.h \
		../../Qt512/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt512/lib/QtCore.framework/Headers/qcoreapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SettingsStore.o SettingsStore.cpp

Utility.o: Utility.cpp ../../Qt512/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt512/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QTextEdit \
		../../Qt512/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt512/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt512/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt512/lib/QtCore.framework/Headers/QRegularExpression \
		../../Qt512/lib/QtCore.framework/Headers/qregularexpression.h \
		../../Qt512/lib/QtCore.framework/Headers/QRegularExpressionMatch \
		../../Qt512/lib/QtCore.framework/Headers/QFile \
		../../Qt512/lib/QtCore.framework/Headers/qfile.h \
		../../Qt512/lib/QtCore.framework/Headers/QFileInfo \
		../../Qt512/lib/QtCore.framework/Headers/qfileinfo.h \
		pageedit_exception.h \
		Utility.h \
		../../Qt512/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt512/lib/QtCore.framework/Headers/qcoreapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utility.o Utility.cpp

WebPageEdit.o: WebPageEdit.cpp ../../Qt512/lib/QtCore.framework/Headers/QTimer \
		../../Qt512/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt512/lib/QtCore.framework/Headers/QDebug \
		../../Qt512/lib/QtCore.framework/Headers/qdebug.h \
		WebPageEdit.h \
		../../Qt512/lib/QtCore.framework/Headers/QObject \
		../../Qt512/lib/QtCore.framework/Headers/qobject.h \
		../../Qt512/lib/QtCore.framework/Headers/QUrl \
		../../Qt512/lib/QtCore.framework/Headers/qurl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WebPageEdit.o WebPageEdit.cpp

WebViewEdit.o: WebViewEdit.cpp ../../Qt512/lib/QtCore.framework/Headers/QEvent \
		../../Qt512/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt512/lib/QtCore.framework/Headers/QEventLoop \
		../../Qt512/lib/QtCore.framework/Headers/qeventloop.h \
		../../Qt512/lib/QtCore.framework/Headers/QDeadlineTimer \
		../../Qt512/lib/QtCore.framework/Headers/qdeadlinetimer.h \
		../../Qt512/lib/QtCore.framework/Headers/QTimer \
		../../Qt512/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt512/lib/QtCore.framework/Headers/QSize \
		../../Qt512/lib/QtCore.framework/Headers/qsize.h \
		../../Qt512/lib/QtCore.framework/Headers/QUrl \
		../../Qt512/lib/QtCore.framework/Headers/qurl.h \
		../../Qt512/lib/QtCore.framework/Headers/QDir \
		../../Qt512/lib/QtCore.framework/Headers/qdir.h \
		../../Qt512/lib/QtCore.framework/Headers/QDebug \
		../../Qt512/lib/QtCore.framework/Headers/qdebug.h \
		Utility.h \
		../../Qt512/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt512/lib/QtCore.framework/Headers/qcoreapplication.h \
		SettingsStore.h \
		../../Qt512/lib/QtGui.framework/Headers/QColor \
		../../Qt512/lib/QtGui.framework/Headers/qcolor.h \
		WebPageEdit.h \
		../../Qt512/lib/QtCore.framework/Headers/QObject \
		../../Qt512/lib/QtCore.framework/Headers/qobject.h \
		WebViewEdit.h \
		Viewer.h \
		Zoomable.h \
		ElementIndex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WebViewEdit.o WebViewEdit.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_javascript.o: qrc_javascript.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_javascript.o qrc_javascript.cpp

moc_MainApplication.o: moc_MainApplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainApplication.o moc_MainApplication.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_Inspector.o: moc_Inspector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Inspector.o moc_Inspector.cpp

moc_SelectCharacter.o: moc_SelectCharacter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SelectCharacter.o moc_SelectCharacter.cpp

moc_SettingsStore.o: moc_SettingsStore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SettingsStore.o moc_SettingsStore.cpp

moc_WebPageEdit.o: moc_WebPageEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WebPageEdit.o moc_WebPageEdit.cpp

moc_WebViewEdit.o: moc_WebViewEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WebViewEdit.o moc_WebViewEdit.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

